name: Manual install

on:
  workflow_dispatch:
    inputs:
      test_run:
        description: 'Run tests after installation'
        required: false
        type: boolean
  pull_request:
    types: [opened, reopened]
    branches:
      - main
    

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "16"

    - name: Install dependencies
      run: npm install

    - name: Run application
      run: npm run build

    - name: Test application
      run: npm test
      if: ${{ github.event.inputs.test_run == 'true' || github.event_name == 'pull_request' }}