name: Manual install

on:
  workflow_dispatch:
    inputs:
      test_run:
        description: 'Run tests after installation'
        required: false
        type: boolean
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: "cicd_database"
          POSTGRES_USER: "cicd_user"
          POSTGRES_PASSWORD: "cicd_password"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "16"

    - name: Install dependencies
      run: npm install

    - name: Run application
      run: npm run build

    - name: Test application
      run: npm test
      if: ${{ github.event.inputs.test_run == 'true' || github.event_name == 'pull_request' }}